package com.aistar.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Job implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.company_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_city
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_year
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_degree
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_need_number
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer jobNeedNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_publish_time
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @DateTimeFormat(pattern = "YYYY-MM-dd")
    private Date jobPublishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_welfare
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobWelfare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_duty
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_demand
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobDemand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_addr_detail
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobAddrDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_min_salary
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private BigDecimal jobMinSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_max_salary
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private BigDecimal jobMaxSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_search_keyword
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String jobSearchKeyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.status
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.other1
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.other2
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.company_id
     *
     * @return the value of job.company_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.company_id
     *
     * @param companyId the value for job.company_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_city
     *
     * @return the value of job.job_city
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobCity() {
        return jobCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_city
     *
     * @param jobCity the value for job.job_city
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobCity(String jobCity) {
        this.jobCity = jobCity == null ? null : jobCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_year
     *
     * @return the value of job.job_year
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobYear() {
        return jobYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_year
     *
     * @param jobYear the value for job.job_year
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobYear(String jobYear) {
        this.jobYear = jobYear == null ? null : jobYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_degree
     *
     * @return the value of job.job_degree
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobDegree() {
        return jobDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_degree
     *
     * @param jobDegree the value for job.job_degree
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobDegree(String jobDegree) {
        this.jobDegree = jobDegree == null ? null : jobDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_need_number
     *
     * @return the value of job.job_need_number
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getJobNeedNumber() {
        return jobNeedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_need_number
     *
     * @param jobNeedNumber the value for job.job_need_number
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobNeedNumber(Integer jobNeedNumber) {
        this.jobNeedNumber = jobNeedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_publish_time
     *
     * @return the value of job.job_publish_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Date getJobPublishTime() {
        return jobPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_publish_time
     *
     * @param jobPublishTime the value for job.job_publish_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobPublishTime(Date jobPublishTime) {
        this.jobPublishTime = jobPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_welfare
     *
     * @return the value of job.job_welfare
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobWelfare() {
        return jobWelfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_welfare
     *
     * @param jobWelfare the value for job.job_welfare
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobWelfare(String jobWelfare) {
        this.jobWelfare = jobWelfare == null ? null : jobWelfare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_duty
     *
     * @return the value of job.job_duty
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobDuty() {
        return jobDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_duty
     *
     * @param jobDuty the value for job.job_duty
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobDuty(String jobDuty) {
        this.jobDuty = jobDuty == null ? null : jobDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_demand
     *
     * @return the value of job.job_demand
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobDemand() {
        return jobDemand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_demand
     *
     * @param jobDemand the value for job.job_demand
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobDemand(String jobDemand) {
        this.jobDemand = jobDemand == null ? null : jobDemand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_addr_detail
     *
     * @return the value of job.job_addr_detail
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobAddrDetail() {
        return jobAddrDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_addr_detail
     *
     * @param jobAddrDetail the value for job.job_addr_detail
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobAddrDetail(String jobAddrDetail) {
        this.jobAddrDetail = jobAddrDetail == null ? null : jobAddrDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_min_salary
     *
     * @return the value of job.job_min_salary
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public BigDecimal getJobMinSalary() {
        return jobMinSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_min_salary
     *
     * @param jobMinSalary the value for job.job_min_salary
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobMinSalary(BigDecimal jobMinSalary) {
        this.jobMinSalary = jobMinSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_max_salary
     *
     * @return the value of job.job_max_salary
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public BigDecimal getJobMaxSalary() {
        return jobMaxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_max_salary
     *
     * @param jobMaxSalary the value for job.job_max_salary
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobMaxSalary(BigDecimal jobMaxSalary) {
        this.jobMaxSalary = jobMaxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_search_keyword
     *
     * @return the value of job.job_search_keyword
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getJobSearchKeyword() {
        return jobSearchKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_search_keyword
     *
     * @param jobSearchKeyword the value for job.job_search_keyword
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobSearchKeyword(String jobSearchKeyword) {
        this.jobSearchKeyword = jobSearchKeyword == null ? null : jobSearchKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.status
     *
     * @return the value of job.status
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.status
     *
     * @param status the value for job.status
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.other1
     *
     * @return the value of job.other1
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.other1
     *
     * @param other1 the value for job.other1
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.other2
     *
     * @return the value of job.other2
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.other2
     *
     * @param other2 the value for job.other2
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", companyId=").append(companyId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobCity=").append(jobCity);
        sb.append(", jobYear=").append(jobYear);
        sb.append(", jobDegree=").append(jobDegree);
        sb.append(", jobNeedNumber=").append(jobNeedNumber);
        sb.append(", jobPublishTime=").append(jobPublishTime);
        sb.append(", jobWelfare=").append(jobWelfare);
        sb.append(", jobDuty=").append(jobDuty);
        sb.append(", jobDemand=").append(jobDemand);
        sb.append(", jobAddrDetail=").append(jobAddrDetail);
        sb.append(", jobMinSalary=").append(jobMinSalary);
        sb.append(", jobMaxSalary=").append(jobMaxSalary);
        sb.append(", jobSearchKeyword=").append(jobSearchKeyword);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}