package com.aistar.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_name
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_num
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Long proNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_size
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Float proSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_color
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String proColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_price
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Float proPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_address
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String proAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_date
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @DateTimeFormat(pattern = "YYYY-MM-dd")
    private Date proDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_id
     *
     * @return the value of product.pro_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_id
     *
     * @param proId the value for product.pro_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_name
     *
     * @return the value of product.pro_name
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_name
     *
     * @param proName the value for product.pro_name
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_num
     *
     * @return the value of product.pro_num
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Long getProNum() {
        return proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_num
     *
     * @param proNum the value for product.pro_num
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProNum(Long proNum) {
        this.proNum = proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_size
     *
     * @return the value of product.pro_size
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Float getProSize() {
        return proSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_size
     *
     * @param proSize the value for product.pro_size
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProSize(Float proSize) {
        this.proSize = proSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_color
     *
     * @return the value of product.pro_color
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getProColor() {
        return proColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_color
     *
     * @param proColor the value for product.pro_color
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProColor(String proColor) {
        this.proColor = proColor == null ? null : proColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_price
     *
     * @return the value of product.pro_price
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Float getProPrice() {
        return proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_price
     *
     * @param proPrice the value for product.pro_price
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProPrice(Float proPrice) {
        this.proPrice = proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_address
     *
     * @return the value of product.pro_address
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getProAddress() {
        return proAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_address
     *
     * @param proAddress the value for product.pro_address
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProAddress(String proAddress) {
        this.proAddress = proAddress == null ? null : proAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_date
     *
     * @return the value of product.pro_date
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Date getProDate() {
        return proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_date
     *
     * @param proDate the value for product.pro_date
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setProDate(Date proDate) {
        this.proDate = proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", proId=").append(proId);
        sb.append(", proName=").append(proName);
        sb.append(", proNum=").append(proNum);
        sb.append(", proSize=").append(proSize);
        sb.append(", proColor=").append(proColor);
        sb.append(", proPrice=").append(proPrice);
        sb.append(", proAddress=").append(proAddress);
        sb.append(", proDate=").append(proDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}