package com.aistar.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class ResumeDeliveryRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.resume_delivery_record_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer resumeDeliveryRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.cust_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.resume_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.job_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.delivery_time
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @DateTimeFormat(pattern = "YYYY-MM-dd")
    private Date deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.delivery_status
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer deliveryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.other1
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_delivery_record.other2
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.resume_delivery_record_id
     *
     * @return the value of resume_delivery_record.resume_delivery_record_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getResumeDeliveryRecordId() {
        return resumeDeliveryRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.resume_delivery_record_id
     *
     * @param resumeDeliveryRecordId the value for resume_delivery_record.resume_delivery_record_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setResumeDeliveryRecordId(Integer resumeDeliveryRecordId) {
        this.resumeDeliveryRecordId = resumeDeliveryRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.cust_id
     *
     * @return the value of resume_delivery_record.cust_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.cust_id
     *
     * @param custId the value for resume_delivery_record.cust_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.resume_id
     *
     * @return the value of resume_delivery_record.resume_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.resume_id
     *
     * @param resumeId the value for resume_delivery_record.resume_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.job_id
     *
     * @return the value of resume_delivery_record.job_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.job_id
     *
     * @param jobId the value for resume_delivery_record.job_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.delivery_time
     *
     * @return the value of resume_delivery_record.delivery_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.delivery_time
     *
     * @param deliveryTime the value for resume_delivery_record.delivery_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.delivery_status
     *
     * @return the value of resume_delivery_record.delivery_status
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.delivery_status
     *
     * @param deliveryStatus the value for resume_delivery_record.delivery_status
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setDeliveryStatus(Integer deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.other1
     *
     * @return the value of resume_delivery_record.other1
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.other1
     *
     * @param other1 the value for resume_delivery_record.other1
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_delivery_record.other2
     *
     * @return the value of resume_delivery_record.other2
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_delivery_record.other2
     *
     * @param other2 the value for resume_delivery_record.other2
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resumeDeliveryRecordId=").append(resumeDeliveryRecordId);
        sb.append(", custId=").append(custId);
        sb.append(", resumeId=").append(resumeId);
        sb.append(", jobId=").append(jobId);
        sb.append(", deliveryTime=").append(deliveryTime);
        sb.append(", deliveryStatus=").append(deliveryStatus);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}