package com.aistar.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class WorkExperienceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public WorkExperienceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andWorkExperiIdIsNull() {
            addCriterion("work_experi_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdIsNotNull() {
            addCriterion("work_experi_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdEqualTo(Integer value) {
            addCriterion("work_experi_id =", value, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdNotEqualTo(Integer value) {
            addCriterion("work_experi_id <>", value, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdGreaterThan(Integer value) {
            addCriterion("work_experi_id >", value, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_experi_id >=", value, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdLessThan(Integer value) {
            addCriterion("work_experi_id <", value, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdLessThanOrEqualTo(Integer value) {
            addCriterion("work_experi_id <=", value, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdIn(List<Integer> values) {
            addCriterion("work_experi_id in", values, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdNotIn(List<Integer> values) {
            addCriterion("work_experi_id not in", values, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdBetween(Integer value1, Integer value2) {
            addCriterion("work_experi_id between", value1, value2, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andWorkExperiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("work_experi_id not between", value1, value2, "workExperiId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNull() {
            addCriterion("resume_id is null");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNotNull() {
            addCriterion("resume_id is not null");
            return (Criteria) this;
        }

        public Criteria andResumeIdEqualTo(Integer value) {
            addCriterion("resume_id =", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotEqualTo(Integer value) {
            addCriterion("resume_id <>", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThan(Integer value) {
            addCriterion("resume_id >", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("resume_id >=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThan(Integer value) {
            addCriterion("resume_id <", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThanOrEqualTo(Integer value) {
            addCriterion("resume_id <=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIn(List<Integer> values) {
            addCriterion("resume_id in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotIn(List<Integer> values) {
            addCriterion("resume_id not in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdBetween(Integer value1, Integer value2) {
            addCriterion("resume_id between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("resume_id not between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIsNull() {
            addCriterion("work_start_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIsNotNull() {
            addCriterion("work_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeEqualTo(Date value) {
            addCriterionForJDBCDate("work_start_time =", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("work_start_time <>", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("work_start_time >", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_start_time >=", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLessThan(Date value) {
            addCriterionForJDBCDate("work_start_time <", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_start_time <=", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIn(List<Date> values) {
            addCriterionForJDBCDate("work_start_time in", values, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("work_start_time not in", values, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_start_time between", value1, value2, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_start_time not between", value1, value2, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIsNull() {
            addCriterion("work_end_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIsNotNull() {
            addCriterion("work_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeEqualTo(Date value) {
            addCriterionForJDBCDate("work_end_time =", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("work_end_time <>", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("work_end_time >", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_end_time >=", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLessThan(Date value) {
            addCriterionForJDBCDate("work_end_time <", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("work_end_time <=", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIn(List<Date> values) {
            addCriterionForJDBCDate("work_end_time in", values, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("work_end_time not in", values, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_end_time between", value1, value2, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("work_end_time not between", value1, value2, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameIsNull() {
            addCriterion("work_company_name is null");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameIsNotNull() {
            addCriterion("work_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameEqualTo(String value) {
            addCriterion("work_company_name =", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameNotEqualTo(String value) {
            addCriterion("work_company_name <>", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameGreaterThan(String value) {
            addCriterion("work_company_name >", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("work_company_name >=", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameLessThan(String value) {
            addCriterion("work_company_name <", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("work_company_name <=", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameLike(String value) {
            addCriterion("work_company_name like", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameNotLike(String value) {
            addCriterion("work_company_name not like", value, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameIn(List<String> values) {
            addCriterion("work_company_name in", values, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameNotIn(List<String> values) {
            addCriterion("work_company_name not in", values, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameBetween(String value1, String value2) {
            addCriterion("work_company_name between", value1, value2, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyNameNotBetween(String value1, String value2) {
            addCriterion("work_company_name not between", value1, value2, "workCompanyName");
            return (Criteria) this;
        }

        public Criteria andWorkPositionIsNull() {
            addCriterion("work_position is null");
            return (Criteria) this;
        }

        public Criteria andWorkPositionIsNotNull() {
            addCriterion("work_position is not null");
            return (Criteria) this;
        }

        public Criteria andWorkPositionEqualTo(String value) {
            addCriterion("work_position =", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionNotEqualTo(String value) {
            addCriterion("work_position <>", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionGreaterThan(String value) {
            addCriterion("work_position >", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionGreaterThanOrEqualTo(String value) {
            addCriterion("work_position >=", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionLessThan(String value) {
            addCriterion("work_position <", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionLessThanOrEqualTo(String value) {
            addCriterion("work_position <=", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionLike(String value) {
            addCriterion("work_position like", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionNotLike(String value) {
            addCriterion("work_position not like", value, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionIn(List<String> values) {
            addCriterion("work_position in", values, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionNotIn(List<String> values) {
            addCriterion("work_position not in", values, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionBetween(String value1, String value2) {
            addCriterion("work_position between", value1, value2, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkPositionNotBetween(String value1, String value2) {
            addCriterion("work_position not between", value1, value2, "workPosition");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentIsNull() {
            addCriterion("work_department is null");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentIsNotNull() {
            addCriterion("work_department is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentEqualTo(String value) {
            addCriterion("work_department =", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotEqualTo(String value) {
            addCriterion("work_department <>", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentGreaterThan(String value) {
            addCriterion("work_department >", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("work_department >=", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentLessThan(String value) {
            addCriterion("work_department <", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentLessThanOrEqualTo(String value) {
            addCriterion("work_department <=", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentLike(String value) {
            addCriterion("work_department like", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotLike(String value) {
            addCriterion("work_department not like", value, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentIn(List<String> values) {
            addCriterion("work_department in", values, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotIn(List<String> values) {
            addCriterion("work_department not in", values, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentBetween(String value1, String value2) {
            addCriterion("work_department between", value1, value2, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkDepartmentNotBetween(String value1, String value2) {
            addCriterion("work_department not between", value1, value2, "workDepartment");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerIsNull() {
            addCriterion("work_company_scaler is null");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerIsNotNull() {
            addCriterion("work_company_scaler is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerEqualTo(String value) {
            addCriterion("work_company_scaler =", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerNotEqualTo(String value) {
            addCriterion("work_company_scaler <>", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerGreaterThan(String value) {
            addCriterion("work_company_scaler >", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerGreaterThanOrEqualTo(String value) {
            addCriterion("work_company_scaler >=", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerLessThan(String value) {
            addCriterion("work_company_scaler <", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerLessThanOrEqualTo(String value) {
            addCriterion("work_company_scaler <=", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerLike(String value) {
            addCriterion("work_company_scaler like", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerNotLike(String value) {
            addCriterion("work_company_scaler not like", value, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerIn(List<String> values) {
            addCriterion("work_company_scaler in", values, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerNotIn(List<String> values) {
            addCriterion("work_company_scaler not in", values, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerBetween(String value1, String value2) {
            addCriterion("work_company_scaler between", value1, value2, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyScalerNotBetween(String value1, String value2) {
            addCriterion("work_company_scaler not between", value1, value2, "workCompanyScaler");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyIsNull() {
            addCriterion("work_company_property is null");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyIsNotNull() {
            addCriterion("work_company_property is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyEqualTo(String value) {
            addCriterion("work_company_property =", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyNotEqualTo(String value) {
            addCriterion("work_company_property <>", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyGreaterThan(String value) {
            addCriterion("work_company_property >", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("work_company_property >=", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyLessThan(String value) {
            addCriterion("work_company_property <", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyLessThanOrEqualTo(String value) {
            addCriterion("work_company_property <=", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyLike(String value) {
            addCriterion("work_company_property like", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyNotLike(String value) {
            addCriterion("work_company_property not like", value, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyIn(List<String> values) {
            addCriterion("work_company_property in", values, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyNotIn(List<String> values) {
            addCriterion("work_company_property not in", values, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyBetween(String value1, String value2) {
            addCriterion("work_company_property between", value1, value2, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkCompanyPropertyNotBetween(String value1, String value2) {
            addCriterion("work_company_property not between", value1, value2, "workCompanyProperty");
            return (Criteria) this;
        }

        public Criteria andWorkDescIsNull() {
            addCriterion("work_desc is null");
            return (Criteria) this;
        }

        public Criteria andWorkDescIsNotNull() {
            addCriterion("work_desc is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDescEqualTo(String value) {
            addCriterion("work_desc =", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescNotEqualTo(String value) {
            addCriterion("work_desc <>", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescGreaterThan(String value) {
            addCriterion("work_desc >", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescGreaterThanOrEqualTo(String value) {
            addCriterion("work_desc >=", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescLessThan(String value) {
            addCriterion("work_desc <", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescLessThanOrEqualTo(String value) {
            addCriterion("work_desc <=", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescLike(String value) {
            addCriterion("work_desc like", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescNotLike(String value) {
            addCriterion("work_desc not like", value, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescIn(List<String> values) {
            addCriterion("work_desc in", values, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescNotIn(List<String> values) {
            addCriterion("work_desc not in", values, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescBetween(String value1, String value2) {
            addCriterion("work_desc between", value1, value2, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkDescNotBetween(String value1, String value2) {
            addCriterion("work_desc not between", value1, value2, "workDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNull() {
            addCriterion("work_type is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNotNull() {
            addCriterion("work_type is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeEqualTo(String value) {
            addCriterion("work_type =", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotEqualTo(String value) {
            addCriterion("work_type <>", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThan(String value) {
            addCriterion("work_type >", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("work_type >=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThan(String value) {
            addCriterion("work_type <", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThanOrEqualTo(String value) {
            addCriterion("work_type <=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLike(String value) {
            addCriterion("work_type like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotLike(String value) {
            addCriterion("work_type not like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIn(List<String> values) {
            addCriterion("work_type in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotIn(List<String> values) {
            addCriterion("work_type not in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeBetween(String value1, String value2) {
            addCriterion("work_type between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotBetween(String value1, String value2) {
            addCriterion("work_type not between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_experience
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 26 09:56:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}