package com.aistar.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class WorkExperience implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_experi_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer workExperiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.resume_id
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer resumeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_start_time
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @DateTimeFormat(pattern = "YYYY-MM-dd")
    private Date workStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_end_time
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @DateTimeFormat(pattern = "YYYY-MM-dd")
    private Date workEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_company_name
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_position
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_department
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_company_scaler
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workCompanyScaler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_company_property
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workCompanyProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_desc
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.work_type
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.status
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.other1
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_experience.other2
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_experi_id
     *
     * @return the value of work_experience.work_experi_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getWorkExperiId() {
        return workExperiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_experi_id
     *
     * @param workExperiId the value for work_experience.work_experi_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkExperiId(Integer workExperiId) {
        this.workExperiId = workExperiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.resume_id
     *
     * @return the value of work_experience.resume_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.resume_id
     *
     * @param resumeId the value for work_experience.resume_id
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setResumeId(Integer resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_start_time
     *
     * @return the value of work_experience.work_start_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Date getWorkStartTime() {
        return workStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_start_time
     *
     * @param workStartTime the value for work_experience.work_start_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkStartTime(Date workStartTime) {
        this.workStartTime = workStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_end_time
     *
     * @return the value of work_experience.work_end_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Date getWorkEndTime() {
        return workEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_end_time
     *
     * @param workEndTime the value for work_experience.work_end_time
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkEndTime(Date workEndTime) {
        this.workEndTime = workEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_company_name
     *
     * @return the value of work_experience.work_company_name
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkCompanyName() {
        return workCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_company_name
     *
     * @param workCompanyName the value for work_experience.work_company_name
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkCompanyName(String workCompanyName) {
        this.workCompanyName = workCompanyName == null ? null : workCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_position
     *
     * @return the value of work_experience.work_position
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkPosition() {
        return workPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_position
     *
     * @param workPosition the value for work_experience.work_position
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkPosition(String workPosition) {
        this.workPosition = workPosition == null ? null : workPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_department
     *
     * @return the value of work_experience.work_department
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkDepartment() {
        return workDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_department
     *
     * @param workDepartment the value for work_experience.work_department
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkDepartment(String workDepartment) {
        this.workDepartment = workDepartment == null ? null : workDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_company_scaler
     *
     * @return the value of work_experience.work_company_scaler
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkCompanyScaler() {
        return workCompanyScaler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_company_scaler
     *
     * @param workCompanyScaler the value for work_experience.work_company_scaler
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkCompanyScaler(String workCompanyScaler) {
        this.workCompanyScaler = workCompanyScaler == null ? null : workCompanyScaler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_company_property
     *
     * @return the value of work_experience.work_company_property
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkCompanyProperty() {
        return workCompanyProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_company_property
     *
     * @param workCompanyProperty the value for work_experience.work_company_property
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkCompanyProperty(String workCompanyProperty) {
        this.workCompanyProperty = workCompanyProperty == null ? null : workCompanyProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_desc
     *
     * @return the value of work_experience.work_desc
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkDesc() {
        return workDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_desc
     *
     * @param workDesc the value for work_experience.work_desc
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkDesc(String workDesc) {
        this.workDesc = workDesc == null ? null : workDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.work_type
     *
     * @return the value of work_experience.work_type
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.work_type
     *
     * @param workType the value for work_experience.work_type
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.status
     *
     * @return the value of work_experience.status
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.status
     *
     * @param status the value for work_experience.status
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.other1
     *
     * @return the value of work_experience.other1
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.other1
     *
     * @param other1 the value for work_experience.other1
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_experience.other2
     *
     * @return the value of work_experience.other2
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_experience.other2
     *
     * @param other2 the value for work_experience.other2
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workExperiId=").append(workExperiId);
        sb.append(", resumeId=").append(resumeId);
        sb.append(", workStartTime=").append(workStartTime);
        sb.append(", workEndTime=").append(workEndTime);
        sb.append(", workCompanyName=").append(workCompanyName);
        sb.append(", workPosition=").append(workPosition);
        sb.append(", workDepartment=").append(workDepartment);
        sb.append(", workCompanyScaler=").append(workCompanyScaler);
        sb.append(", workCompanyProperty=").append(workCompanyProperty);
        sb.append(", workDesc=").append(workDesc);
        sb.append(", workType=").append(workType);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}