package com.aistar.mapper;

import com.aistar.pojo.ProjectExperience;
import com.aistar.pojo.ProjectExperienceExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ProjectExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int countByExample(ProjectExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int deleteByExample(ProjectExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int deleteByPrimaryKey(Integer projectExperiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int insert(ProjectExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int insertSelective(ProjectExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    List<ProjectExperience> selectByExample(ProjectExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    ProjectExperience selectByPrimaryKey(Integer projectExperiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProjectExperience record, @Param("example") ProjectExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByExample(@Param("record") ProjectExperience record, @Param("example") ProjectExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_experience
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByPrimaryKey(ProjectExperience record);
}