package com.aistar.mapper;

import com.aistar.pojo.ResumeDeliveryRecord;
import com.aistar.pojo.ResumeDeliveryRecordExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ResumeDeliveryRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int countByExample(ResumeDeliveryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int deleteByExample(ResumeDeliveryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int deleteByPrimaryKey(Integer resumeDeliveryRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int insert(ResumeDeliveryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int insertSelective(ResumeDeliveryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    List<ResumeDeliveryRecord> selectByExample(ResumeDeliveryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    ResumeDeliveryRecord selectByPrimaryKey(Integer resumeDeliveryRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") ResumeDeliveryRecord record, @Param("example") ResumeDeliveryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByExample(@Param("record") ResumeDeliveryRecord record, @Param("example") ResumeDeliveryRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByPrimaryKeySelective(ResumeDeliveryRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_delivery_record
     *
     * @mbggenerated Wed Feb 26 09:56:38 CST 2020
     */
    int updateByPrimaryKey(ResumeDeliveryRecord record);
}